name: Build and Release

on:
  push:
    tags:
      - 'v*' # работает при тегах типа v1.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Artifact (Zip)
        run: |
          zip -r project-v1.zip main.py test.py app.log

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: project-v1.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}